- name: Bootstrap machines
  hosts: all
  vars:
    do_bootstrap: true
  tasks:
    - name: Do boostrap
      include_role: 
        name: bootstrap
      when: do_bootstrap
- import_playbook: hostnamestoragenode.yaml
- import_playbook: hostnamemanagernode.yaml
- import_playbook: hostnameworkers.yaml
- import_playbook: commonkeys.yaml
- import_playbook: sharecommonkeys.yaml
- import_playbook: userfiles.yaml
- import_playbook: firewall.yaml
- import_playbook: install-hadoop.yaml
- import_playbook: hadoop-manager.yaml
- import_playbook: hadoop-datanodes.yaml
- import_playbook: hadoop-final.yaml
- import_playbook: install-spark.yaml
- import_playbook: spark-manager.yaml
