- name: Install and configure hadoop
  hosts: workers:storagenode
  become: true
  become_user: root
  tasks:
  - name: create datanode
    ansible.builtin.file:
      path: /opt/hadoop_tmp/hdfs/datanode
      state: directory
  - name: Set permissions
    ansible.builtin.shell: chown -R almalinux:almalinux /opt/hadoop_tmp