---
- name: set hostnames
  become: true
  ansible.builtin.hostname:
    name: "{% if (inventory_hostname in groups['managernode']) %}managernode{% elif 
      inventory_hostname in groups['storagenode'] %}storagenode{% else 
      %}workernode{{lookup('ansible.utils.index_of', groups['workers'], 'eq', inventory_hostname) + 1 }}{% endif %}"
    use: systemd

- name: create ssh key
  import_tasks: commonkeys.yaml
  when: inventory_hostname in groups['managernode']
- name: share keys among cluster
  import_tasks: sharecommonkeys.yaml

- name: set ssh config
  ansible.builtin.copy:
    src: ./files/ssh_config
    dest: /home/almalinux/.ssh/config

- name: enable ufw firewall
  import_tasks: firewall.yaml
