- name: Install merizo search requirements
  hosts: workers
  become: true
  tasks:
#   - name: Install conda
#     ansible.builtin.dnf:
#       name: conda
#       state: present
#   - name: Download merizo search
#     ansible.builtin.git: 
#       repo: https://github.com/psipred/merizo_search.git
#       dest: /home/almalinux/merizo_search
#       clone: true
    - name: Use torch-cpu
      ansible.builtin.shell: sed -i '/torch==/d' /home/almalinux/merizo_search/merizo_search/programs/Merizo/requirements.txt
    
#   - name: Change dir
#     ansible.builtin.shell: cd /home/almalinux/merizo_search
#   - name: Create env
#     ansible.builtin.shell: conda create --yes -n merizo_search python=3.9
#   - name: Reports opt-out
#     ansible.builtin.shell: conda config --set report_errors false
    - name: Initialize conda
      ansible.builtin.shell: |
        conda create --yes -n merizo_search python=3.9
        eval "$(conda shell.bash hook)"
        conda init bash
        source ~/.bashrc
        conda activate merizo_search
        conda install pytorch==2.0.1 cpuonly -c pytorch
        pip install -r /home/almalinux/merizo_search/merizo_search/programs/Merizo/requirements.txt
        conda install --yes -c pytorch faiss-cpu
        pyspark
    - name: test env
      ansible.builtin.shell: |
        eval "$(conda shell.bash hook)"
        conda activate merizo_search
        pyspark
  # - name: Source bashrc
  #   ansible.builtin.shell: source /home/almalinux/.bashrc
  # - name: Activate env
  #   ansible.builtin.shell: conda activate merizo_search
  # - name: Install requirements
  #   ansible.builtin.shell: 
  # - name: Install requirements (faiss)
  #   ansible.builtin.shell: conda install --yes -c pytorch faiss-cpu
