- name: Create minio dir on data disk
  become: true
  ansible.builtin.file:
    path: /data/minio
    owner: minio-user
    group: minio-user
    mode: "0700"
    state: directory
- name: Install Minio RPM
  become: true
  ansible.builtin.dnf:
    name: https://dl.min.io/server/minio/release/linux-amd64/minio.rpm
    state: present
- name: Install Minio command-line
  become: true
  ansible.builtin.get_url:
    dest: /usr/local/bin/mc
    url: "https://dl.min.io/client/mc/release/linux-amd64/mc"
    mode: "0755"

- name: Set up environment file
  become: true
  ansible.builtin.template:
    src: templates/minio.j2
    dest:  /etc/default/minio
    owner: root
    group: minio-user
    mode: "0640"
- name: Start Minio
  become: true
  ansible.builtin.systemd_service:
    name: minio
    state: started
    enabled: true

- name: Copy minio pass to almalinux directory
  ansible.builtin.copy:
    owner: almalinux
    group: almalinux
    mode: "0600"
    src: "./.miniopass"
    dest: "/home/almalinux/miniopass"
- name: Setup mc for local access
  ansible.builtin.template:
    src: templates/mc_config.json.j2
    dest:  /home/almalinux/.mc/config.json
    owner: almalinux
    group: almalinux
    mode: "0600"
